@startuml
'https://plantuml.com/activity-diagram-beta

start
    :The input number is
    provided in R0 at start;


    if (R0 == 2) then (true)
        :R0 = 1;
        stop
    else (false)
        if (modulo-2 of R0) then (not 0);
            :Save R1 in stack;
            :R1 = 3;

            while (R0 > sqrt(R1)) equals (true)
                if (modulo-(R1) of R0) then (not 0)
                else (0)
                    :R0 = 0;
                    stop
                endif
                :R1 = R1+2;
            endwhile (false)
        else (0)
            :R0 = 0;
            stop
        endif

        :R0 = 1;
        stop
    endif


@enduml
