#include "cards.h"
#include "yukon.h"

Card allCards[] = {
        {.number = 1, .suit = CLUBS, .revealed = false},
        {.number = 2, .suit = CLUBS, .revealed = false},
        {.number = 3, .suit = CLUBS, .revealed = false},
        {.number = 4, .suit = CLUBS, .revealed = false},
        {.number = 5, .suit = CLUBS, .revealed = false},
        {.number = 6, .suit = CLUBS, .revealed = false},
        {.number = 7, .suit = CLUBS, .revealed = false},
        {.number = 8, .suit = CLUBS, .revealed = false},
        {.number = 9, .suit = CLUBS, .revealed = false},
        {.number = 10, .suit = CLUBS, .revealed = false},
        {.number = 11, .suit = CLUBS, .revealed = false},
        {.number = 12, .suit = CLUBS, .revealed = false},
        {.number = 13, .suit = CLUBS, .revealed = false},
        {.number = 1, .suit = DIAMONDS, .revealed = false},
        {.number = 2, .suit = DIAMONDS, .revealed = false},
        {.number = 3, .suit = DIAMONDS, .revealed = false},
        {.number = 4, .suit = DIAMONDS, .revealed = false},
        {.number = 5, .suit = DIAMONDS, .revealed = false},
        {.number = 6, .suit = DIAMONDS, .revealed = false},
        {.number = 7, .suit = DIAMONDS, .revealed = false},
        {.number = 8, .suit = DIAMONDS, .revealed = false},
        {.number = 9, .suit = DIAMONDS, .revealed = false},
        {.number = 10, .suit = DIAMONDS, .revealed = false},
        {.number = 11, .suit = DIAMONDS, .revealed = false},
        {.number = 12, .suit = DIAMONDS, .revealed = false},
        {.number = 13, .suit = DIAMONDS, .revealed = false},
        {.number = 1, .suit = HEARTS, .revealed = false},
        {.number = 2, .suit = HEARTS, .revealed = false},
        {.number = 3, .suit = HEARTS, .revealed = false},
        {.number = 4, .suit = HEARTS, .revealed = false},
        {.number = 5, .suit = HEARTS, .revealed = false},
        {.number = 6, .suit = HEARTS, .revealed = false},
        {.number = 7, .suit = HEARTS, .revealed = false},
        {.number = 8, .suit = HEARTS, .revealed = false},
        {.number = 9, .suit = HEARTS, .revealed = false},
        {.number = 10, .suit = HEARTS, .revealed = false},
        {.number = 11, .suit = HEARTS, .revealed = false},
        {.number = 12, .suit = HEARTS, .revealed = false},
        {.number = 13, .suit = HEARTS, .revealed = false},
        {.number = 1, .suit = SPADES, .revealed = false},
        {.number = 2, .suit = SPADES, .revealed = false},
        {.number = 3, .suit = SPADES, .revealed = false},
        {.number = 4, .suit = SPADES, .revealed = false},
        {.number = 5, .suit = SPADES, .revealed = false},
        {.number = 6, .suit = SPADES, .revealed = false},
        {.number = 7, .suit = SPADES, .revealed = false},
        {.number = 8, .suit = SPADES, .revealed = false},
        {.number = 9, .suit = SPADES, .revealed = false},
        {.number = 10, .suit = SPADES, .revealed = false},
        {.number = 11, .suit = SPADES, .revealed = false},
        {.number = 12, .suit = SPADES, .revealed = false},
        {.number = 13, .suit = SPADES, .revealed = false}
};