#ifndef MACHINE_ORIENTED_PROGRAMMING_PROJECT_2_CARDS_H
#define MACHINE_ORIENTED_PROGRAMMING_PROJECT_2_CARDS_H

#include "yukon.h"

extern Card cards[53];

#endif //MACHINE_ORIENTED_PROGRAMMING_PROJECT_2_CARDS_H
